"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup
import sys

APP = ['app.py']

if sys.platform == 'darwin':
    extra_options = dict(
        setup_requires=['py2app'],
        app=APP,
        options=dict(py2app=dict(argv_emulation=True)),
    )
elif sys.platform == 'win32':
    extra_options = dict(
        setup_requires=['py2exe'],
        app=APP,
    )
else:
    extra_options = dict(
        scripts=APP,
    )

setup(
    name="SubFinder",
    **extra_options
)
