"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup
import sys
import shutil

cert_file = 'assets/cacert.pem'

APP = ['app.py']

if sys.platform == 'darwin':
    extra_options = dict(
        setup_requires=['py2app'],
        app=APP,
        options=dict(
            py2app=dict(
                argv_emulation=True, 
                resources=','.join([cert_file, ])
            )
        ),
    )
elif sys.platform == 'win32':
    extra_options = dict(
        setup_requires=['py2exe'],
        app=APP,
    )
else:
    extra_options = dict(
        scripts=APP,
    )

setup(
    name="SubFinder",
    **extra_options
)

if sys.platform == 'darwin':
    shutil.make_archive('./dist/SubFinder.app', format='gztar', root_dir='./dist', base_dir='./')
elif sys.platform == 'win32':
    shutil.make_archive('./dist/SubFinder.exe', format='gztar', root_dir='./dist', base_dir='./')


